name: Simple Website Ping Keep-Alive

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ping_website:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Website to Keep Supabase Active

        run: |
          echo "Pinging site"

          curl -s -f -o /dev/null "https://satkhira-alumni.vercel.app"
          echo "Ping successful."
