name: Simple Website Ping Keep-Alive

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ping_website:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Website to Keep Supabase Active

        run: |
          echo "Pinging site"

          curl -s -f -S "https://satkhira-alumni.vercel.app" > response.txt
          if [ $? -ne 0 ]; then
            echo "Ping FAILED."
            exit 1
          fi
          echo "Ping successful. First 10 lines of content:"
          head -n 10 response.txt
          echo "..."
